jobs:

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    PROFILE: 'profiles/windows_x86_64_visual_studio_15_2017'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - template: templates/setup-conan.yml
  - script: |
      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) googletest kwc/stable
      conan upload --confirm googletest

      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) qt kwc/stable
      conan upload --confirm Qt

      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) VTK kwc/stable
      conan upload --confirm VTK

      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) vtk-dicom kwc/stable
      conan upload --confirm vtk-dicom
  strategy:
    matrix:
      Release:
        BUILD_TYPE: 'Release'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  variables:
    PROFILE: 'profiles/macos_x86_64_apple_clang_11_0'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      brew update
      brew install conan || brew upgrade conan
  - template: templates/setup-conan.yml
  - script: |
      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) googletest kwc/stable
      conan upload --confirm googletest

      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) qt kwc/stable
      conan upload --confirm Qt

      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) VTK kwc/stable
      conan upload --confirm VTK

      conan create -pr $(PROFILE) -r kwc -b outdated -s build_type=$(BUILD_TYPE) vtk-dicom kwc/stable
      conan upload --confirm vtk-dicom
  strategy:
    matrix:
      Release:
          BUILD_TYPE: 'Release'

