jobs:

- job: Windows_VS2017
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    PROFILE: 'profiles/windows_x86_64_visual_studio_15_2017'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - template: templates/install-conan.yml
  - template: templates/setup-conan.yml
  - template: templates/build-package.yml
    parameters:
      packages: ["googletest", "qt", "tbb", "vtk", "vtk_dicom"]
  strategy:
    matrix:
      Release:
        BUILD_TYPE: 'Release'

- job: Windows_VS2019
  pool:
    vmImage: 'windows-2019'
  variables:
    PROFILE: 'profiles/windows_x86_64_visual_studio_17_2019'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - template: templates/install-conan.yml
  - template: templates/setup-conan.yml
  - template: templates/build-package.yml
    parameters:
      packages: ["googletest", "qt", "tbb", "vtk", "vtk_dicom"]
  strategy:
    matrix:
      Release:
        BUILD_TYPE: 'Release'

- job: Ubuntu_Linux_18.04
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    PROFILE: 'profiles/ubuntu_x86_64_gcc_7'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - template: templates/install-conan.yml
  - script: echo "##vso[task.setvariable variable=PATH]${PATH}:~/.local/bin/"
  - template: templates/setup-conan.yml
  - template: templates/build-package.yml
    parameters:
      packages: ["googletest", "qt", "tbb", "vtk", "vtk_dicom"]
  strategy:
    matrix:
      Release:
        BUILD_TYPE: 'Release'

- job: macOS_10.14
  pool:
    vmImage: 'macOS-10.14'
  variables:
    PROFILE: 'profiles/macos_x86_64_apple_clang_11_0'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      brew update
      brew install conan || brew upgrade conan
  - template: templates/install-conan.yml
  - template: templates/setup-conan.yml
  - template: templates/build-package.yml
    parameters:
      packages: ["googletest", "qt", "tbb", "vtk", "vtk_dicom"]
  strategy:
    matrix:
      Release:
          BUILD_TYPE: 'Release'

