jobs:

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      pip install --upgrade pip
      pip install conan --upgrade
      pip install conan_package_tools bincrafters_package_tools
      set CONAN_VISUAL_VERSIONS="15"
      # pushd googletest && python build.py && popd
      # pushd qt && python build.py && popd
      pushd VTK && python build.py && popd
    env:
      CONAN_PASSWORD: $(CONAN_PASSWORD)
  strategy:
    matrix:
      Release:
        CONAN_BUILD_TYPES: Release

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      sudo xcode-select -switch /Applications/Xcode_${XCODE_VERSION}.app/
      clang --version
      pip install --upgrade pip
      pip install conan --upgrade
      pip install conan_package_tools bincrafters_package_tools
      # pushd googletest && python build.py && popd
      # pushd qt && python build.py && popd
      # pushd VTK && python build.py && popd
    env:
      CONAN_PASSWORD: $(CONAN_PASSWORD)
  strategy:
    matrix:
      Xcode-10.0:
        CONAN_APPLE_CLANG_VERSIONS: 10.0
        XCODE_VERSION: 10

