parameters:
  packages: ["googletest", "qt", "tbb", "vtk", "vtk_dicom"]
jobs:

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    PROFILE: 'profiles/windows_x86_64_visual_studio_15_2017'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - template: templates/setup-conan.yml
  - ${{ each pkg in parameters.packages }}:
    - script: |
        conan create -pr $(PROFILE) -r kwc -b outdated -s build_Type=$(BUILD_TYPE) ${{ pkg }}
        conan upload -r kwc --all --confirm ${{ pkg }}
  strategy:
    matrix:
      Release:
        BUILD_TYPE: 'Release'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  variables:
    PROFILE: 'profiles/macos_x86_64_apple_clang_11_0'
  timeoutInMinutes: 0
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      brew update
      brew install conan || brew upgrade conan
  - template: templates/setup-conan.yml
  - ${{ each pkg in parameters.packages }}:
    - script: |
        conan create -pr $(PROFILE) -r kwc -b outdated -s build_Type=$(BUILD_TYPE) ${{ pkg }}
        conan upload -r kwc --all --confirm ${{ pkg }}
  strategy:
    matrix:
      Release:
          BUILD_TYPE: 'Release'

